### ISSUE TITLE
Script to generate pickle File of Veri776 Benchmark

### ISSUE THREAD

**Issue by MAdil45** [silverbulletmdc/PVEN#14]
Hi Everyone,  I am trying to train the network on Veri776 benchmark. Fir that I need script to generate pickle files of Veri776. However, I couldn't find the script to generate them. As mentioned in the repository, there is no script in the example/preprocess_data directory for Veri776 Benchmark. Could please help me to figure out this or may be guiding me in the right direction.
Thanks:

**Comment by silverbulletmdc** [comment]
Sorry. I have forgotten to add the generate_pkl.py to the git repository in the last commit. I have added this file in the latest commit. Just run `git pull` to get it.

**Comment by MAdil45** [comment]
@silverbulletmdc  Thanks for uploading the file. Much appreciated.
