### ISSUE TITLE
NameError: name 'path' is not defined

### ISSUE THREAD

**Issue by MAdil45** [silverbulletmdc/PVEN#15]
Hi. I am trying to generate description pickle file for veri776 benchmark. I have  provided the input and output path, however, I am getting error of  Path is not defined. Could you please provide the guidance of how to handle this.
Thanks. 
![Screenshot from 2020-10-26 11-22-46](https://user-images.githubusercontent.com/36837450/97130889-a1553980-177d-11eb-8310-6aedfc260834.png)

**Comment by silverbulletmdc** [comment]
Thanks for your response. I have fixed it.

**Comment by MAdil45** [comment]
@silverbulletmdc  Thank you so much. However, it showed an error of no module Path. I tried from pathlib import Path, which solved it. Also on line number 41, it should be pkl.dump(output_dict, f), not pickle.dump(output_dic,f). 
Thanks again. Much appreciated.
