### ISSUE TITLE
About the evalution on VehicleID dataset

### ISSUE THREAD

**Issue by abcdvzz** [silverbulletmdc/PVEN#27]
I trained a model on VehicleID dataset using baseline and the training process is reasonable. But when I evaluate the model, I got nan% map. Could you please check it?

**Comment by abcdvzz** [comment]
Anyone can answer my question?

**Comment by xieyuhaoli** [comment]
i get the same problem，did you solve it?

**Comment by silverbulletmdc** [comment]
I have fixed it.
