### ISSUE TITLE
About the "common visible attention" ?

### ISSUE THREAD

**Issue by Ariellsc** [silverbulletmdc/PVEN#28]
Thanks for your great work, but I still have some confusion:

By reading your code, I have not found some process as you said in your paper that "We aggregate the features by common-visible attention to formulate the triplet loss of local features"

**Comment by silverbulletmdc** [comment]
https://github.com/silverbulletmdc/PVEN/blob/master/examples/parsing_reid/math_tools.py#L190

**Comment by Ariellsc** [comment]
thx
