### ISSUE TITLE
缺少portch3d

### ISSUE THREAD

**Issue by PeterWangfor** [silverbulletmdc/PVEN#32]
请问是要在linux上运行吗

**Comment by silverbulletmdc** [comment]
请问是哪个文件报的错？这个仓库应该不需要pytorch3d

**Comment by PeterWangfor** [comment]
cd examples/parsing python veri776_poly2mask.py --json-path poly.json --output-path ../outputs/veri776_parsing3165这一步提示缺少pytorch3d


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "silverbulletmdc/PVEN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [silverbulletmdc/PVEN] 缺少portch3d (#32)





 
请问是哪个文件报的错？这个仓库应该不需要pytorch3d

**Comment by silverbulletmdc** [comment]
已修复
