### ISSUE TITLE
预训练模型加载错误

### ISSUE THREAD

**Issue by jiezhang165** [silverbulletmdc/PVEN#33]
您好博士，我下载了你们提供的预训练模型，当我运行代码 !python examples/parsing/generate_masks.py --model-path 'outputs/veriwild_reid.pth' --reid-pkl-path 'outputs/veri776.pkl' --output-path 'outputs/veri776_masks' 以生成masks时出现以下错误：
Traceback (most recent call last):
  File "examples/parsing/generate_masks.py", line 57, in <module>
    model = model.cuda()
AttributeError: 'collections.OrderedDict' object has no attribute 'cuda'

似乎pth文件并未成功加载，我尝试了添加代码  model.load_state_dict(torch.load(PATH))， 但没有解决问题。

**Comment by silverbulletmdc** [comment]
你用的模型不是parsing的，用另一个

**Comment by jiezhang165** [comment]
感谢博士回复，我昨天发现了这个问题。不过我生成的VeRi数据集的masks全是黑色，print之后发现masks矩阵全是0。请问需要改部分代码吗？

**Comment by jiezhang165** [comment]
我目前在尝试自己训练paring model。在veri776_poly2mask.py中：
def poly2mask(polys, classes, shape):
    mask = np.zeros(shape, dtype=np.uint8)
    for poly, class_ in zip(polys, classes):
        poly = np.array(poly)
        poly[:, 0] *= mask.shape[1]
        poly[:, 1] *= mask.shape[0]
        poly = poly.astype(np.int)
        cv2.fillPoly(mask, [poly], class_ ）
return mask

masks一开始就被定义成了二维，class_ 的值是1-4，所以生成的masks几乎是全黑。我将mask矩阵定义成了三维，生成了论文中描述的彩色mask，但在后续的training中产生了维度错误。如果我将cv2.fillPoly(mask, [poly], class_ ）改为 cv2.fillPoly(mask, [poly], class_  * 50），就能看到灰度值不同而且视觉上很明显的mask，请问不是彩色的mask会对训练结果产生影响吗？博士你们提供的parsing模型是在彩色的mask还是二维的mask上训练的？

**Comment by jiezhang165** [comment]
博士您好，我跳过了mask，直接进行用veriwild模型对veri776进行了测试，ReID的结果：
[I 210408 12:28:22 main:473] mAP: 54.9%
[I 210408 12:28:22 main:475] CMC curve, Rank-1  :81.70%
[I 210408 12:28:22 main:475] CMC curve, Rank-5  :88.02%
[I 210408 12:28:22 main:475] CMC curve, Rank-10 :90.64%
这个结果是不是说明vehicle part parser没有生效，不过给我的感觉，这个模型迁移后的表现已经十分不错了，就是mAP有些低。

**Comment by silverbulletmdc** [comment]
mask的值是1234，不要改。如果想用于可视化就单独处理下。程序中会根据mask值生成one-shot的masks。
