### ISSUE TITLE
about <VeRi_PATH> and VeRi-776 dataset

### ISSUE THREAD

**Issue by Shreyas-Bhat** [silverbulletmdc/PVEN#36]
Hello!
I have some trouble with following the following code - python generate_pkl.py veri776 --input-path <VeRi_PATH>--output-path ../outputs/veri776.pkl

What shall I put as the <VeRi_PATH> as the veri-776 dataset is not present in the repo. Please correct me if I am wrong.
Thanks for your work!
![image](https://user-images.githubusercontent.com/56354373/122911140-9be3d980-d374-11eb-931e-1d8baf0ffe5e.png)

**Comment by silverbulletmdc** [comment]
You should download the VERI776 dataset by yourself and pass the root path of the dataset as input path.
