### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/veri776_b64_parsing.yml'

### ISSUE THREAD

**Issue by Shreyas-Bhat** [silverbulletmdc/PVEN#38]
There doesn't seem to be veri776_b64_parsing.yml, please help me resolve this

Thank you

**Comment by qianchengshuai** [comment]
> 好像没有veri776_b64_parsing.yml，请帮我解决
> 
> 谢谢

I didn't find it either, did you solve it?

**Comment by qianchengshuai** [comment]
> There doesn't seem to be veri776_b64_parsing.yml, please help me resolve this
> 
> Thank you

I didn't find it either, did you solve it?

**Comment by Shreyas-Bhat** [comment]
> > There doesn't seem to be veri776_b64_parsing.yml, please help me resolve this
> > Thank you
> 
> I didn't find it either, did you solve it?

No. I am still awaiting a response

**Comment by qianchengshuai** [comment]
> > > There doesn't seem to be veri776_b64_parsing.yml, please help me resolve this
> > > Thank you
> > 
> > 
> > I didn't find it either, did you solve it?
> 
> No. I am still awaiting a response


> > > There doesn't seem to be veri776_b64_parsing.yml, please help me resolve this
> > > Thank you
> > 
> > 
> > I didn't find it either, did you solve it?
> 
> No. I am still awaiting a response

OK，thanks

**Comment by qianchengshuai** [comment]
> > > There doesn't seem to be veri776_b64_parsing.yml, please help me resolve this
> > > Thank you
> > 
> > 
> > I didn't find it either, did you solve it?
> 
> No. I am still awaiting a response

OK,thanks

**Comment by silverbulletmdc** [comment]
It should be `veri776_b64_pven.yml`. I have fixed it in Readme.

**Comment by Shreyas-Bhat** [comment]
> It should be `veri776_b64_pven.yml`. I have fixed it in Readme.

Thank you
