### ISSUE TITLE
爆内存问题

### ISSUE THREAD

**Issue by nicefuu** [silverbulletmdc/PVEN#40]
你好，我之前16G内存最多只能跑到20个epoch，换了32G内存最多也只能跑到90多个epoch，这是我设置问题吗？还是我内存太小了O.O

**Comment by silverbulletmdc** [comment]
可以试着降低train_num_workers

**Comment by nicefuu** [comment]
> 可以试着降低train_num_workers

谢谢，我在main.py 478行metric.reset() 后面添加了 gc.collect()解决问题了
