### ISSUE TITLE
AttributeError: Can't pickle local object 'AlbuRandomErasing.<locals>.wrapper'

### ISSUE THREAD

**Issue by chen8573** [silverbulletmdc/PVEN#55]
作者您好，您有没有遇到过这个问题,在遍历train_loader时报错:
![image](https://github.com/silverbulletmdc/PVEN/assets/117328029/88635cb2-7594-4a01-88d6-3f93a6c1b413)
应该是AlbuRandomErasing数据增强的问题
![image](https://github.com/silverbulletmdc/PVEN/assets/117328029/2908a392-e1e9-4bb2-a46d-d1e72d78460b)

![image](https://github.com/silverbulletmdc/PVEN/assets/117328029/ae24c989-2108-44a8-a74b-c580150dc892)
我将AlbuRandomErasing这个数据增强取消掉可以正常运行，请问这种情况有好的解决办法吗？

**Comment by silverbulletmdc** [comment]
降低一下albu的版本吧
